// Generated by gencpp from file kortex_driver/FindIndexResponse.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_FINDINDEXRESPONSE_H
#define KORTEX_DRIVER_MESSAGE_FINDINDEXRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kortex_driver
{
template <class ContainerAllocator>
struct FindIndexResponse_
{
  typedef FindIndexResponse_<ContainerAllocator> Type;

  FindIndexResponse_()
    : index(0)
    , grip(0)  {
    }
  FindIndexResponse_(const ContainerAllocator& _alloc)
    : index(0)
    , grip(0)  {
  (void)_alloc;
    }



   typedef int8_t _index_type;
  _index_type index;

   typedef int8_t _grip_type;
  _grip_type grip;





  typedef boost::shared_ptr< ::kortex_driver::FindIndexResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::FindIndexResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FindIndexResponse_

typedef ::kortex_driver::FindIndexResponse_<std::allocator<void> > FindIndexResponse;

typedef boost::shared_ptr< ::kortex_driver::FindIndexResponse > FindIndexResponsePtr;
typedef boost::shared_ptr< ::kortex_driver::FindIndexResponse const> FindIndexResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::FindIndexResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::FindIndexResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::FindIndexResponse_<ContainerAllocator1> & lhs, const ::kortex_driver::FindIndexResponse_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.grip == rhs.grip;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::FindIndexResponse_<ContainerAllocator1> & lhs, const ::kortex_driver::FindIndexResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::FindIndexResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::FindIndexResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::FindIndexResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::FindIndexResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::FindIndexResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::FindIndexResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::FindIndexResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc335e982131613152f901a4d2b0914b";
  }

  static const char* value(const ::kortex_driver::FindIndexResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc335e9821316131ULL;
  static const uint64_t static_value2 = 0x52f901a4d2b0914bULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::FindIndexResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/FindIndexResponse";
  }

  static const char* value(const ::kortex_driver::FindIndexResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::FindIndexResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 index\n"
"int8 grip\n"
"\n"
;
  }

  static const char* value(const ::kortex_driver::FindIndexResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::FindIndexResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.grip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindIndexResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::FindIndexResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::FindIndexResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "index: ";
    Printer<int8_t>::stream(s, indent + "  ", v.index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "grip: ";
    Printer<int8_t>::stream(s, indent + "  ", v.grip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_FINDINDEXRESPONSE_H
