// Generated by gencpp from file kortex_driver/FindIndexRequest.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_FINDINDEXREQUEST_H
#define KORTEX_DRIVER_MESSAGE_FINDINDEXREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kortex_driver
{
template <class ContainerAllocator>
struct FindIndexRequest_
{
  typedef FindIndexRequest_<ContainerAllocator> Type;

  FindIndexRequest_()
    {
    }
  FindIndexRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::kortex_driver::FindIndexRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::FindIndexRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FindIndexRequest_

typedef ::kortex_driver::FindIndexRequest_<std::allocator<void> > FindIndexRequest;

typedef boost::shared_ptr< ::kortex_driver::FindIndexRequest > FindIndexRequestPtr;
typedef boost::shared_ptr< ::kortex_driver::FindIndexRequest const> FindIndexRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::FindIndexRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::FindIndexRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::FindIndexRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::FindIndexRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::FindIndexRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::FindIndexRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::FindIndexRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::FindIndexRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::FindIndexRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::kortex_driver::FindIndexRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::FindIndexRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/FindIndexRequest";
  }

  static const char* value(const ::kortex_driver::FindIndexRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::FindIndexRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::kortex_driver::FindIndexRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::FindIndexRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindIndexRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::FindIndexRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::kortex_driver::FindIndexRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_FINDINDEXREQUEST_H
