// Generated by gencpp from file kortex_driver/SendState.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_SENDSTATE_H
#define KORTEX_DRIVER_MESSAGE_SENDSTATE_H

#include <ros/service_traits.h>


#include <kortex_driver/SendStateRequest.h>
#include <kortex_driver/SendStateResponse.h>


namespace kortex_driver
{

struct SendState
{

typedef SendStateRequest Request;
typedef SendStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendState
} // namespace kortex_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_driver::SendState > {
  static const char* value()
  {
    return "2db8f4ad9fe7fd5f3afc52b1481c1ea1";
  }

  static const char* value(const ::kortex_driver::SendState&) { return value(); }
};

template<>
struct DataType< ::kortex_driver::SendState > {
  static const char* value()
  {
    return "kortex_driver/SendState";
  }

  static const char* value(const ::kortex_driver::SendState&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_driver::SendStateRequest> should match
// service_traits::MD5Sum< ::kortex_driver::SendState >
template<>
struct MD5Sum< ::kortex_driver::SendStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::SendState >::value();
  }
  static const char* value(const ::kortex_driver::SendStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::SendStateRequest> should match
// service_traits::DataType< ::kortex_driver::SendState >
template<>
struct DataType< ::kortex_driver::SendStateRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::SendState >::value();
  }
  static const char* value(const ::kortex_driver::SendStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_driver::SendStateResponse> should match
// service_traits::MD5Sum< ::kortex_driver::SendState >
template<>
struct MD5Sum< ::kortex_driver::SendStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::SendState >::value();
  }
  static const char* value(const ::kortex_driver::SendStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::SendStateResponse> should match
// service_traits::DataType< ::kortex_driver::SendState >
template<>
struct DataType< ::kortex_driver::SendStateResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::SendState >::value();
  }
  static const char* value(const ::kortex_driver::SendStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_SENDSTATE_H
