// Generated by gencpp from file kortex_driver/SendStateRequest.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_SENDSTATEREQUEST_H
#define KORTEX_DRIVER_MESSAGE_SENDSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kortex_driver
{
template <class ContainerAllocator>
struct SendStateRequest_
{
  typedef SendStateRequest_<ContainerAllocator> Type;

  SendStateRequest_()
    : indicies()  {
    }
  SendStateRequest_(const ContainerAllocator& _alloc)
    : indicies(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _indicies_type;
  _indicies_type indicies;





  typedef boost::shared_ptr< ::kortex_driver::SendStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::SendStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendStateRequest_

typedef ::kortex_driver::SendStateRequest_<std::allocator<void> > SendStateRequest;

typedef boost::shared_ptr< ::kortex_driver::SendStateRequest > SendStateRequestPtr;
typedef boost::shared_ptr< ::kortex_driver::SendStateRequest const> SendStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::SendStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::SendStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::SendStateRequest_<ContainerAllocator1> & lhs, const ::kortex_driver::SendStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.indicies == rhs.indicies;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::SendStateRequest_<ContainerAllocator1> & lhs, const ::kortex_driver::SendStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::SendStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::SendStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::SendStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::SendStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::SendStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::SendStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::SendStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59995a16fd277aa8e4abbdca6b7b9199";
  }

  static const char* value(const ::kortex_driver::SendStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59995a16fd277aa8ULL;
  static const uint64_t static_value2 = 0xe4abbdca6b7b9199ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::SendStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/SendStateRequest";
  }

  static const char* value(const ::kortex_driver::SendStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::SendStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] indicies\n"
;
  }

  static const char* value(const ::kortex_driver::SendStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::SendStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.indicies);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::SendStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::SendStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "indicies: ";
    if (v.indicies.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.indicies.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int8_t>::stream(s, true ? std::string() : indent + "    ", v.indicies[i]);
    }
    if (v.indicies.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_SENDSTATEREQUEST_H
